### PR TITLE
Add Metal render backend

### PR DESCRIPTION
**Pull request by warrenm**
This PR adds support for Metal on both SDL2 and Sokol platforms when running atop macOS.

Enabling Metal rendering in a high_impact app is as simple as defining `RENDER_METAL`, enabling Objective-C Automatic Reference Counting (ARC), and linking against Metal (or MetalKit, for Sokol). I have played Biolab Disaster from start to finish with this renderer and believe it to have 1:1 feature parity with the existing desktop GL renderer.

### CODE REVIEW

**Comment by phoboslab** [comment]
Very cool, thank you so much! Will test this later today.

Does Metal support some kind of "bindless textures"? The whole texture atlas handling for the OpenGL renderer was just the easiest way to facilitate this for different GL versions and is thus only an implementation detail. I don't mind the code duplication; just wondering if there would be an easier way with Metal.

Same with the `quadBuffer` actually - just a basic way to minimize draw calls to the driver.

**Comment by warrenm** [comment]
Sure, I've pushed an update to do bindless-style rendering using Metal argument buffers. I also fixed a couple of issues that could cause abnormally high CPU usage. 

One lingering question I have is about texture borders. They're still implemented (and now actually tested), but I'm not certain they're needed when using one texture per sprite/spritesheet. Do you have an opinion on whether they should be removed or not in this case?

**Comment by phoboslab** [comment]
Just tried compiling the two sample games: works as advertised :)

And yes, the border is only necessary to prevent bleed for the texture atlas. It's not even required for pixel style games (if you're not scaling sprites), which is why it's disabled by default. Let me know if you want to remove it. I'd merge this either way. This is great!

**Comment by warrenm** [comment]
All right, amazing. I've removed border support and tightened things up. Sounds like we're in ship-it territory. Let me know if anything else needs adjustment, even if it's stylistic. It's a privilege to contribute to bringing such a legendary project into the modern era.

**Comment by phoboslab** [comment]
Thanks again, great work! 

I've added the `RENDER=METAL` option in the Makefile of the sample games (https://github.com/phoboslab/high_biolab/commit/8bad1607ab19419e6a5cb7610a79208bddea28cd); happy to see that the engine's architecture for allowing different rendering backends seems to work out!

**Pull request merged**
